{
	"id": "CVE-2021-32284",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2021-32284",
				"description": "An issue was discovered in gravity through 0.8.1. A NULL pointer dereference exists in the function ircode_register_pop_context_protect() located in gravity_ircode.c. It allows an attacker to cause Denial of Service.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
							"base_score": 6.8,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 6.8,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 6.8,
							"nvd_environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
							"base_score": 7.8,
							"base_severity": "HIGH",
							"temporal_score": 7.8,
							"temporal_severity": "HIGH",
							"environmental_score": 7.8,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-476"
						]
					}
				],
				"references": [
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/marcobambini/gravity/issues/321"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2021-32284"
					}
				],
				"published": "2021-09-20T16:15:10.647Z",
				"modified": "2021-10-02T03:08:13.317Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"vulnerable": true,
														"fix_status": {
															"class": "unknown"
														},
														"package": {
															"cpe": "cpe:2.3:a:creolabs:gravity:*:*:*:*:*:*:*:*"
														},
														"affected": {
															"type": "semver",
															"range": [
																{
																	"le": "0.8.1"
																}
															]
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2021/CVE-2021-32284.json"
		]
	}
}
