{
	"id": "CVE-2023-6110",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2023-6110",
				"description": "A flaw was found in OpenStack. When a user tries to delete a non-existing access rule in it's scope, it deletes other existing access rules which are not associated with any application credentials.",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "secalert@redhat.com",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:L",
							"base_score": 5.5,
							"base_severity": "MEDIUM",
							"temporal_score": 5.5,
							"temporal_severity": "MEDIUM",
							"environmental_score": 5.5,
							"environmental_severity": "MEDIUM"
						}
					}
				],
				"references": [
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6110"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/errata/RHSA-2024:2737"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/errata/RHSA-2024:2769"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/security/cve/CVE-2023-6110"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2212960"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://code.engineering.redhat.com/gerrit/gitweb?p=python-openstackclient.git;a=commit;h=7a7c364bdd7b2cd2b56e73724110710a68d58abf"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://review.opendev.org/c/openstack/python-openstackclient/+/888697"
					}
				],
				"published": "2024-11-17T11:15:06.097Z",
				"modified": "2024-11-18T17:11:17.393Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2023/CVE-2023-6110.json"
		]
	}
}
