{
	"id": "CVE-2020-29651",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-29651",
				"description": "A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
							"base_score": 5,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 5,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 5,
							"nvd_environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v31",
						"source": "nvd@nist.gov",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"NVD-CWE-Other"
						]
					}
				],
				"references": [
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/pytest-dev/py/issues/256"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/pytest-dev/py/pull/257"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/AYWNYEV3FGDHPIHX4DDUDMFZ6NLCQRC4/"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CHDTINIBJZ67T3W74QTBIY5LPKAXEOGR/"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://www.oracle.com/security-alerts/cpujul2022.html"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2020-29651"
					}
				],
				"published": "2020-12-09T07:15:12.533Z",
				"modified": "2023-11-07T03:21:32.9Z"
			},
			"ecosystems": [
				"cpe"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "cpe",
			"criteria": {
				"operator": "OR",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"package": {
													"cpe": "cpe:2.3:a:oracle:zfs_storage_appliance_kit:8.8:*:*:*:*:*:*:*"
												}
											}
										]
									}
								]
							}
						]
					},
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"package": {
													"cpe": "cpe:2.3:a:pytest:py:*:*:*:*:*:*:*:*"
												},
												"affected": {
													"type": "semver",
													"range": [
														{
															"le": "1.9.0"
														}
													]
												}
											}
										]
									}
								]
							}
						]
					},
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"package": {
													"cpe": "cpe:2.3:o:fedoraproject:fedora:32:*:*:*:*:*:*:*"
												}
											}
										]
									},
									{
										"operator": "OR",
										"criterions": [
											{
												"vulnerable": true,
												"package": {
													"cpe": "cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:*:*"
												}
											}
										]
									}
								]
							}
						]
					}
				]
			}
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2020/CVE-2020-29651.json"
		]
	}
}
