{
	"id": "CVE-2018-25108",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2018-25108",
				"description": "An unauthenticated remote attacker can cause a DoS in the controller due toÂ uncontrolled resource consumption.",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "info@cert.vde.com",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "info@cert.vde.com",
						"cwe": [
							"CWE-770"
						]
					}
				],
				"references": [
					{
						"source": "info@cert.vde.com",
						"url": "https://cert.vde.com/en/advisories/VDE-2018-013"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2018-25108"
					}
				],
				"published": "2025-01-16T11:15:06.85Z",
				"modified": "2025-01-16T11:15:06.85Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2018/CVE-2018-25108.json"
		]
	}
}
