{
	"id": "CVE-2024-4030",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2024-4030",
				"description": "On Windows a directory returned by tempfile.mkdtemp() would not always have permissions set to restrict reading and writing to the temporary directory by other users, instead usually inheriting the correct permissions from the default location. Alternate configurations or users without a profile directory may not have the intended permissions.\n\nIf you’re not using Windows or haven’t changed the temporary directory location then you aren’t affected by this vulnerability. On other platforms the returned directory is consistently readable and writable only by the current user.\n\nThis issue was caused by Python not supporting Unix permissions on Windows. The fix adds support for Unix “700” for the mkdir function on Windows which is used by mkdtemp() to ensure the newly created directory has the proper permissions.\n",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
							"base_score": 7.1,
							"base_severity": "HIGH",
							"temporal_score": 7.1,
							"temporal_severity": "HIGH",
							"environmental_score": 7.1,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "cna@python.org",
						"cwe": [
							"CWE-276"
						]
					}
				],
				"references": [
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/35c799d79177b962ddace2fa068101465570a29a"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/5130731c9e779b97d00a24f54cdce73ce9975dfd"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/66f8bb76a15e64a1bb7688b177ed29e26230fdee"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/6d0850c4c8188035643586ab4d8ec2468abd699e"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/81939dad77001556c527485d31a2d0f4a759033e"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/8ed546679524140d8282175411fd141fe7df070d"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/91e3669e01245185569d09e9e6e11641282971ee"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/94591dca510c796c7d40e9b4167ea56f2fdf28ca"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/c8f868dc52f98011d0f9b459b6487920bfb0ac4d"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/d86b49411753bf2c83291e3a14ae43fefded2f84"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/e1dfa978b1ad210d551385ad8073ec6154f53763"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/commit/eb29e2f5905da93333d1ce78bc98b151e763ff46"
					},
					{
						"source": "cna@python.org",
						"url": "https://github.com/python/cpython/issues/118486"
					},
					{
						"source": "cna@python.org",
						"url": "https://mail.python.org/archives/list/security-announce@python.org/thread/PRGS5OR3N3PNPT4BMV2VAGN5GMUI5636/"
					},
					{
						"source": "cna@python.org",
						"url": "https://security.netapp.com/advisory/ntap-20240705-0005/"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-4030"
					}
				],
				"published": "2024-05-07T21:15:09.467Z",
				"modified": "2024-07-05T16:15:05.52Z"
			},
			"ecosystems": [
				"cpe"
			]
		}
	],
	"data_source": "nvd-api-cve"
}
