{
	"id": "CVE-2024-37400",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2024-37400",
				"description": "An out of bounds read in Ivanti Connect Secure before version 22.7R2.3 allows a remote unauthenticated attacker to trigger an infinite loop, causing a denial of service.",
				"severity": [
					{
						"type": "cvss_v30",
						"source": "support@hackerone.com",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
						"cwe": [
							"CWE-125"
						]
					}
				],
				"references": [
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37400"
					},
					{
						"source": "support@hackerone.com",
						"url": "https://forums.ivanti.com/s/article/Security-Advisory-Ivanti-Connect-Secure-ICS-Ivanti-Policy-Secure-IPS-Ivanti-Secure-Access-Client-ISAC-Multiple-CVEs"
					}
				],
				"published": "2024-11-13T02:15:18.163Z",
				"modified": "2024-11-13T17:35:04.687Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2024/CVE-2024-37400.json"
		]
	}
}
