{
	"id": "CVE-2016-10321",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2016-10321",
				"description": "web2py before 2.14.6 does not properly check if a host is denied before verifying passwords, allowing a remote attacker to perform brute-force attacks.",
				"severity": [
					{
						"type": "cvss_v2",
						"source": "nvd@nist.gov",
						"cvss_v2": {
							"vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
							"base_score": 5,
							"nvd_base_severity": "MEDIUM",
							"temporal_score": 5,
							"nvd_temporal_severity": "MEDIUM",
							"environmental_score": 5,
							"nvd_environmental_severity": "MEDIUM"
						}
					},
					{
						"type": "cvss_v30",
						"source": "nvd@nist.gov",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
							"base_score": 9.8,
							"base_severity": "CRITICAL",
							"temporal_score": 9.8,
							"temporal_severity": "CRITICAL",
							"environmental_score": 9.8,
							"environmental_severity": "CRITICAL"
						}
					}
				],
				"cwe": [
					{
						"source": "nvd@nist.gov",
						"cwe": [
							"CWE-254"
						]
					}
				],
				"references": [
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://github.com/web2py/web2py/commit/944d8bd8f3c5cf8ae296fc03d149056c65358426"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://github.com/web2py/web2py/issues/1585#issuecomment-284317919"
					},
					{
						"source": "af854a3a-2127-422b-91ae-364da2661108",
						"url": "https://usn.ubuntu.com/4030-1/"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/web2py/web2py/commit/944d8bd8f3c5cf8ae296fc03d149056c65358426"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://github.com/web2py/web2py/issues/1585#issuecomment-284317919"
					},
					{
						"source": "cve@mitre.org",
						"url": "https://usn.ubuntu.com/4030-1/"
					},
					{
						"source": "nvd.nist.gov",
						"url": "https://nvd.nist.gov/vuln/detail/CVE-2016-10321"
					}
				],
				"published": "2017-04-10T14:59:00.217Z",
				"modified": "2024-11-21T02:43:47.067Z"
			},
			"segments": [
				{
					"ecosystem": "cpe"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "cpe",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterias": [
							{
								"operator": "OR",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "OR",
												"criterions": [
													{
														"type": "version",
														"version": {
															"vulnerable": true,
															"fix_status": {
																"class": "unknown"
															},
															"package": {
																"type": "cpe",
																"cpe": "cpe:2.3:a:web2py:web2py:*:*:*:*:*:*:*:*"
															},
															"affected": {
																"type": "semver",
																"range": [
																	{
																		"le": "2.14.5"
																	}
																]
															}
														}
													}
												]
											}
										]
									}
								]
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "nvd-api-cve",
		"raws": [
			"vuls-data-raw-nvd-api-cve/2016/CVE-2016-10321.json"
		]
	}
}
